package igu;

import javax.swing.*;
import java.awt.*;
import igu.PPrincipal;
import main.Crud;


/**
 *
 * @author ferfr
 */
public class Dashboard extends javax.swing.JFrame {

    
    //crear otras pantallas
    public static P_Camarero p_camarero = new P_Camarero();
    public static PVComandas pvComandas = new PVComandas();
  
    
    //crear crud
    Crud crud = new Crud();
    
    
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        CrearC = new javax.swing.JMenu();
        VerC = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        Contenido.setMaximumSize(new java.awt.Dimension(800, 577));
        Contenido.setMinimumSize(new java.awt.Dimension(800, 577));
        Contenido.setPreferredSize(new java.awt.Dimension(800, 577));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(70, 23));

        CrearC.setText("Crear Comanda");
        CrearC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearCMouseClicked(evt);
            }
        });
        jMenuBar1.add(CrearC);

        VerC.setText("Ver Comanda");
        VerC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerCMouseClicked(evt);
            }
        });
        jMenuBar1.add(VerC);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCMouseClicked
        
        if(PPrincipal.getUsuarioApp().equals("cocina")){
            crud.cambiarUsuarioApp("cocina");
            JOptionPane.showMessageDialog(null, "No tiene persmisos para entrar");
            
        }else if(PPrincipal.getUsuarioApp().equals("mesero")){
            cambiarPantalla(p_camarero);
            System.out.println("mesero");
            crud.cambiarUsuarioApp("mesero");
        }else{
            cambiarPantalla(p_camarero);
            crud.cambiarUsuarioApp("admin");
        }
        
        
    }//GEN-LAST:event_CrearCMouseClicked

    private void VerCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerCMouseClicked
        cambiarPantalla(pvComandas);
    }//GEN-LAST:event_VerCMouseClicked

    public void cambiarPantalla(JPanel p1){
        
        p1.setSize(800,600);
        p1.setLocation(0,0);
        
        this.Contenido.removeAll();
        this.Contenido.add(p1,BorderLayout.CENTER);
        this.Contenido.revalidate();
        this.Contenido.repaint();
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JMenu CrearC;
    private javax.swing.JMenu VerC;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
